-- Seed listings for Wichita (city_slug = 'wichita')
-- Run after schema.sql

insert into public.listings (title, description, price, category, condition, location, lat, lng, city_slug, image_url, seller_name, is_garage_sale, sale_type, sale_date, sale_date_iso, posted_hours_ago, is_active) values
('Craftsman Lawn Mower — Self-Propelled', 'Runs great, tune-up last spring. Pick up only.', 180, 'Outdoors', 'good', 'COLLEGE HILL', 37.6923, -97.3187, 'wichita', '/listings/lawnmower.png', 'Mike D.', false, null, null, null, 2, true),
('Cedar Porch Bench w/ Cup Holders', 'Handmade cedar bench. Built-in cup holders. Never been rained on.', 275, 'Furniture', 'like new', 'RIVERSIDE CITIZENS ASSOC', 37.7012, -97.3598, 'wichita', '/listings/bench.png', 'Jordan K.', false, null, null, null, 5, true),
('Neighborhood Garage Sale — Sat 9am', '8 households. Furniture, kids'' toys, kitchenware, vinyl records, plants. Cash + Venmo.', 0, 'Sales', null, 'ORCHARD BREEZE', 37.6801, -97.3642, 'wichita', '/listings/grill.png', 'Elm St Neighbors', true, 'garage', 'Sat, Jun 8 · 9am–3pm', '2026-06-08', null, true),
('PS5 Digital Edition', 'Works perfect. Selling because I upgraded.', 350, 'Electronics', 'good', 'NORTHEAST HEIGHTS', 37.6941, -97.2876, 'wichita', '/listings/ps5.png', 'Devon L.', false, null, null, null, 1, true),
('TV Stand w/ Electric Fireplace', 'Fits up to 65". Fireplace insert lights up, heater works.', 220, 'Furniture', 'good', 'CROWN HEIGHTS NORTH', 37.6788, -97.3102, 'wichita', '/listings/tv-stand.png', 'Priya S.', false, null, null, null, 11, true),
('Estate Sale — 3 Generations', 'Antique furniture, retro electronics, tools, kitchen, jewelry. Early birds welcome.', 0, 'Sales', null, 'FAIRMOUNT', 37.6897, -97.2714, 'wichita', '/listings/retro-consoles.png', 'The Chen Family', true, 'estate', 'Sun, Jun 9 · 8am–2pm', '2026-06-09', null, true),
('FLEX 12" Cordless Miter Saw', '24V, barely used. Has original box and blade.', 420, 'Tools', 'like new', 'DELANO', 37.6831, -97.3734, 'wichita', '/listings/miter-saw.png', 'Sam T.', false, null, null, null, 3, true),
('Maytag Maxima Washer & Dryer Set', 'Both work perfectly. Moving, can''t take them. Must take both.', 650, 'Appliances', 'good', 'SUNNYSIDE', 37.6659, -97.3301, 'wichita', '/listings/washer-dryer.png', 'Renee F.', false, null, null, null, 26, true),
('Singer Tradition Sewing Machine', 'Lightly used. All feet and manual included.', 75, 'Crafts', 'fair', 'HISTORIC MIDTOWN CITIZENS ASSOC', 37.6872, -97.3427, 'wichita', '/listings/sewing-machine.png', 'Alex M.', false, null, null, null, 48, true),
('Block Party Garage Sale — Multi-Family', '12+ homes participating. Maps at the corner. Live music + lemonade stand.', 0, 'Sales', null, 'COLLEGE HILL', 37.6955, -97.3201, 'wichita', '/listings/lawnmower.png', '20th St Block', true, 'garage', 'Sat, Jun 15 · 10am–4pm', '2026-06-15', null, true),
('GMC Yukon AT4 — Lifted & Loaded', '2022, 34k miles. AT4 trim, aftermarket wheels and tires. Clean title.', 58500, 'Vehicles', 'like new', 'ORCHARD PARK', 37.7001, -97.3891, 'wichita', '/listings/gmc.png', 'Hana O.', false, null, null, null, 4, true),
('Retro Console Lot — NES, SNES, PS1', 'All tested and working. Includes controllers and some games.', 290, 'Electronics', 'good', 'NORTH RIVERSIDE', 37.7044, -97.3541, 'wichita', '/listings/retro-consoles.png', 'Marcus B.', false, null, null, null, 72, true),
('Mercedes G-Wagon AMG', '2018 G63. Black on black. Low miles, mint condition.', 89000, 'Vehicles', 'like new', 'MATLOCK HEIGHTS', 37.6748, -97.2801, 'wichita', '/listings/g-wagon.png', 'Tyler R.', false, null, null, null, 168, true),
('Piper Seneca Twin Engine', '1979 PA-34. 4200 TT airframe, fresh annual. IFR equipped.', 185000, 'Vehicles', 'fair', 'PLANEVIEW UNITED', 37.6499, -97.4330, 'wichita', '/listings/plane.png', 'Aviation Grp', false, null, null, null, 336, true),
('Char-Broil 4-Burner Gas Grill', 'Works well, just upgraded. Side burner included.', 95, 'Outdoors', 'fair', 'SOUTHWEST', 37.6711, -97.3589, 'wichita', '/listings/grill.png', 'Dave K.', false, null, null, null, 8, true),
('Sony CRT TV — 27"', 'Perfect for retro gaming. Composite + coax inputs.', 40, 'Electronics', 'for parts', 'CROWN HEIGHTS SOUTH', 37.6819, -97.3055, 'wichita', '/listings/crt-tv.png', 'Old Timer', false, null, null, null, 120, true);
